package main.java;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

public class App implements Runnable
{
    /** */
    private static final int WIDTH = 500;
    private static final int HEIGHT = 500;
    
    /** The list of all Fighters able to be displayed by the program. */
    private ArrayList<Fighter> fighters;
    
    /** The main window of the program. */
    private JFrame window;
    /** The canvas that previews of the thumbnails will be drawn to. */
    private Canvas canvas;
    /** The selection box for the first Fighter. */
    private JComboBox<Fighter> fighterBox1;
    /** The selection box for the second Fighter. */
    private JComboBox<Fighter> fighterBox2;
    /** The selection box for the first Fighter's Variant. */
    private JComboBox<Variant> variantBox1;
    /** The selection box for the second Fighter's Variant. */
    private JComboBox<Variant> variantBox2;
    /** The input field for inputting a name for the first player. */
    private JTextField nameBox1;
    /** The input field for inputting a name for the first player. */
    private JTextField nameBox2;
    /** A button to generate and save the thumbnail described by the current state of the input fields. */
    private JButton generate;
    /** A button to reset the input fields. */
    private JButton reset;
    /** The graphics object used to paint the canvas. */
    private Graphics2D g;
    
    @Override
    public void run()
    {
        //todo implement
        window = new JFrame();
        window.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        window.setSize(WIDTH, HEIGHT);
        
//        fighterBox1 = new JComboBox<Fighter>(fighters);
//        fighterBox2 = new JComboBox<Fighter>(fighters);
//        variantBox1 = new JComboBox<Variant>();
//        variantBox2 = new JComboBox<Variant>();
        nameBox1 = new JTextField();
        nameBox2 = new JTextField();
        
        window.setVisible(true);
        
        
//        window.add();
//        for ()
//        {
//
//        }
    }
    
    /**
     * Loads a data file from the resources folder.
     * @param fileName the name of the file to be loaded.
     * @return the file in raw String form.
     */
    private String loadFile(String fileName)
    {
        StringBuilder output = new StringBuilder();
        
        //Get file from resources folder
        ClassLoader classLoader = getClass().getClassLoader();
        File toLoad = new File(classLoader.getResource(fileName).getFile());
        try
        {
            Scanner scanner = new Scanner(toLoad);
            while (scanner.hasNextLine())
            {
                //todo load costume data and character data this way
//                String line = scanner.nextLine();
//                output.append(line).append("\n");
            }
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }
        return output.toString();
    }
    
    /**
     * Exports a thumbnail that was just generated by the app.
     * @param output The image to be saved.
     */
    private static void export(BufferedImage output)
    {
        //todo implement
    }
}
